/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package net.gbcoder.gblib.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.persistence.UserPersistence;

import net.gbcoder.gblib.model.Author;
import net.gbcoder.gblib.service.AuthorLocalService;
import net.gbcoder.gblib.service.persistence.AuthorPersistence;
import net.gbcoder.gblib.service.persistence.BookPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the Author local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link net.gbcoder.gblib.service.impl.AuthorLocalServiceImpl}.
 * </p>
 *
 * @author GL
 * @see net.gbcoder.gblib.service.impl.AuthorLocalServiceImpl
 * @see net.gbcoder.gblib.service.AuthorLocalServiceUtil
 * @generated
 */
public abstract class AuthorLocalServiceBaseImpl extends BaseLocalServiceImpl
	implements AuthorLocalService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link net.gbcoder.gblib.service.AuthorLocalServiceUtil} to access the Author local service.
	 */

	/**
	 * Adds the Author to the database. Also notifies the appropriate model listeners.
	 *
	 * @param author the Author
	 * @return the Author that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Author addAuthor(Author author) throws SystemException {
		author.setNew(true);

		return authorPersistence.update(author);
	}

	/**
	 * Creates a new Author with the primary key. Does not add the Author to the database.
	 *
	 * @param authorId the primary key for the new Author
	 * @return the new Author
	 */
	@Override
	public Author createAuthor(long authorId) {
		return authorPersistence.create(authorId);
	}

	/**
	 * Deletes the Author with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param authorId the primary key of the Author
	 * @return the Author that was removed
	 * @throws PortalException if a Author with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Author deleteAuthor(long authorId)
		throws PortalException, SystemException {
		return authorPersistence.remove(authorId);
	}

	/**
	 * Deletes the Author from the database. Also notifies the appropriate model listeners.
	 *
	 * @param author the Author
	 * @return the Author that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Author deleteAuthor(Author author) throws SystemException {
		return authorPersistence.remove(author);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(Author.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return authorPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link net.gbcoder.gblib.model.impl.AuthorModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return authorPersistence.findWithDynamicQuery(dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link net.gbcoder.gblib.model.impl.AuthorModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return authorPersistence.findWithDynamicQuery(dynamicQuery, start, end,
			orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return authorPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) throws SystemException {
		return authorPersistence.countWithDynamicQuery(dynamicQuery, projection);
	}

	@Override
	public Author fetchAuthor(long authorId) throws SystemException {
		return authorPersistence.fetchByPrimaryKey(authorId);
	}

	/**
	 * Returns the Author with the matching UUID and company.
	 *
	 * @param uuid the Author's UUID
	 * @param  companyId the primary key of the company
	 * @return the matching Author, or <code>null</code> if a matching Author could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public Author fetchAuthorByUuidAndCompanyId(String uuid, long companyId)
		throws SystemException {
		return authorPersistence.fetchByUuid_C_First(uuid, companyId, null);
	}

	/**
	 * Returns the Author matching the UUID and group.
	 *
	 * @param uuid the Author's UUID
	 * @param groupId the primary key of the group
	 * @return the matching Author, or <code>null</code> if a matching Author could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public Author fetchAuthorByUuidAndGroupId(String uuid, long groupId)
		throws SystemException {
		return authorPersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the Author with the primary key.
	 *
	 * @param authorId the primary key of the Author
	 * @return the Author
	 * @throws PortalException if a Author with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public Author getAuthor(long authorId)
		throws PortalException, SystemException {
		return authorPersistence.findByPrimaryKey(authorId);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return authorPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns the Author with the matching UUID and company.
	 *
	 * @param uuid the Author's UUID
	 * @param  companyId the primary key of the company
	 * @return the matching Author
	 * @throws PortalException if a matching Author could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public Author getAuthorByUuidAndCompanyId(String uuid, long companyId)
		throws PortalException, SystemException {
		return authorPersistence.findByUuid_C_First(uuid, companyId, null);
	}

	/**
	 * Returns the Author matching the UUID and group.
	 *
	 * @param uuid the Author's UUID
	 * @param groupId the primary key of the group
	 * @return the matching Author
	 * @throws PortalException if a matching Author could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public Author getAuthorByUuidAndGroupId(String uuid, long groupId)
		throws PortalException, SystemException {
		return authorPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the Authors.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link net.gbcoder.gblib.model.impl.AuthorModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of Authors
	 * @param end the upper bound of the range of Authors (not inclusive)
	 * @return the range of Authors
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public List<Author> getAuthors(int start, int end)
		throws SystemException {
		return authorPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of Authors.
	 *
	 * @return the number of Authors
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public int getAuthorsCount() throws SystemException {
		return authorPersistence.countAll();
	}

	/**
	 * Updates the Author in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param author the Author
	 * @return the Author that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Author updateAuthor(Author author) throws SystemException {
		return authorPersistence.update(author);
	}

	/**
	 * Returns the Author local service.
	 *
	 * @return the Author local service
	 */
	public net.gbcoder.gblib.service.AuthorLocalService getAuthorLocalService() {
		return authorLocalService;
	}

	/**
	 * Sets the Author local service.
	 *
	 * @param authorLocalService the Author local service
	 */
	public void setAuthorLocalService(
		net.gbcoder.gblib.service.AuthorLocalService authorLocalService) {
		this.authorLocalService = authorLocalService;
	}

	/**
	 * Returns the Author remote service.
	 *
	 * @return the Author remote service
	 */
	public net.gbcoder.gblib.service.AuthorService getAuthorService() {
		return authorService;
	}

	/**
	 * Sets the Author remote service.
	 *
	 * @param authorService the Author remote service
	 */
	public void setAuthorService(
		net.gbcoder.gblib.service.AuthorService authorService) {
		this.authorService = authorService;
	}

	/**
	 * Returns the Author persistence.
	 *
	 * @return the Author persistence
	 */
	public AuthorPersistence getAuthorPersistence() {
		return authorPersistence;
	}

	/**
	 * Sets the Author persistence.
	 *
	 * @param authorPersistence the Author persistence
	 */
	public void setAuthorPersistence(AuthorPersistence authorPersistence) {
		this.authorPersistence = authorPersistence;
	}

	/**
	 * Returns the Book local service.
	 *
	 * @return the Book local service
	 */
	public net.gbcoder.gblib.service.BookLocalService getBookLocalService() {
		return bookLocalService;
	}

	/**
	 * Sets the Book local service.
	 *
	 * @param bookLocalService the Book local service
	 */
	public void setBookLocalService(
		net.gbcoder.gblib.service.BookLocalService bookLocalService) {
		this.bookLocalService = bookLocalService;
	}

	/**
	 * Returns the Book remote service.
	 *
	 * @return the Book remote service
	 */
	public net.gbcoder.gblib.service.BookService getBookService() {
		return bookService;
	}

	/**
	 * Sets the Book remote service.
	 *
	 * @param bookService the Book remote service
	 */
	public void setBookService(
		net.gbcoder.gblib.service.BookService bookService) {
		this.bookService = bookService;
	}

	/**
	 * Returns the Book persistence.
	 *
	 * @return the Book persistence
	 */
	public BookPersistence getBookPersistence() {
		return bookPersistence;
	}

	/**
	 * Sets the Book persistence.
	 *
	 * @param bookPersistence the Book persistence
	 */
	public void setBookPersistence(BookPersistence bookPersistence) {
		this.bookPersistence = bookPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();

		PersistedModelLocalServiceRegistryUtil.register("net.gbcoder.gblib.model.Author",
			authorLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"net.gbcoder.gblib.model.Author");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return Author.class;
	}

	protected String getModelClassName() {
		return Author.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = authorPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = net.gbcoder.gblib.service.AuthorLocalService.class)
	protected net.gbcoder.gblib.service.AuthorLocalService authorLocalService;
	@BeanReference(type = net.gbcoder.gblib.service.AuthorService.class)
	protected net.gbcoder.gblib.service.AuthorService authorService;
	@BeanReference(type = AuthorPersistence.class)
	protected AuthorPersistence authorPersistence;
	@BeanReference(type = net.gbcoder.gblib.service.BookLocalService.class)
	protected net.gbcoder.gblib.service.BookLocalService bookLocalService;
	@BeanReference(type = net.gbcoder.gblib.service.BookService.class)
	protected net.gbcoder.gblib.service.BookService bookService;
	@BeanReference(type = BookPersistence.class)
	protected BookPersistence bookPersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private AuthorLocalServiceClpInvoker _clpInvoker = new AuthorLocalServiceClpInvoker();
}