/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package net.gbcoder.gblib.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Book service. Represents a row in the &quot;Book&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link net.gbcoder.gblib.model.impl.BookModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link net.gbcoder.gblib.model.impl.BookImpl}.
 * </p>
 *
 * @author GL
 * @see Book
 * @see net.gbcoder.gblib.model.impl.BookImpl
 * @see net.gbcoder.gblib.model.impl.BookModelImpl
 * @generated
 */
public interface BookModel extends BaseModel<Book>, StagedGroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a Book model instance should use the {@link Book} interface instead.
	 */

	/**
	 * Returns the primary key of this Book.
	 *
	 * @return the primary key of this Book
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this Book.
	 *
	 * @param primaryKey the primary key of this Book
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this Book.
	 *
	 * @return the uuid of this Book
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this Book.
	 *
	 * @param uuid the uuid of this Book
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the book ID of this Book.
	 *
	 * @return the book ID of this Book
	 */
	public long getBookId();

	/**
	 * Sets the book ID of this Book.
	 *
	 * @param bookId the book ID of this Book
	 */
	public void setBookId(long bookId);

	/**
	 * Returns the group ID of this Book.
	 *
	 * @return the group ID of this Book
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this Book.
	 *
	 * @param groupId the group ID of this Book
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this Book.
	 *
	 * @return the company ID of this Book
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this Book.
	 *
	 * @param companyId the company ID of this Book
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this Book.
	 *
	 * @return the user ID of this Book
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this Book.
	 *
	 * @param userId the user ID of this Book
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this Book.
	 *
	 * @return the user uuid of this Book
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this Book.
	 *
	 * @param userUuid the user uuid of this Book
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this Book.
	 *
	 * @return the user name of this Book
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this Book.
	 *
	 * @param userName the user name of this Book
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this Book.
	 *
	 * @return the create date of this Book
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this Book.
	 *
	 * @param createDate the create date of this Book
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this Book.
	 *
	 * @return the modified date of this Book
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this Book.
	 *
	 * @param modifiedDate the modified date of this Book
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the book name of this Book.
	 *
	 * @return the book name of this Book
	 */
	@AutoEscape
	public String getBookName();

	/**
	 * Sets the book name of this Book.
	 *
	 * @param bookName the book name of this Book
	 */
	public void setBookName(String bookName);

	/**
	 * Returns the book pricae of this Book.
	 *
	 * @return the book pricae of this Book
	 */
	public double getBookPricae();

	/**
	 * Sets the book pricae of this Book.
	 *
	 * @param bookPricae the book pricae of this Book
	 */
	public void setBookPricae(double bookPricae);

	/**
	 * Returns the book date of this Book.
	 *
	 * @return the book date of this Book
	 */
	public Date getBookDate();

	/**
	 * Sets the book date of this Book.
	 *
	 * @param bookDate the book date of this Book
	 */
	public void setBookDate(Date bookDate);

	/**
	 * Returns the author ID of this Book.
	 *
	 * @return the author ID of this Book
	 */
	public long getAuthorId();

	/**
	 * Sets the author ID of this Book.
	 *
	 * @param authorId the author ID of this Book
	 */
	public void setAuthorId(long authorId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(net.gbcoder.gblib.model.Book book);

	@Override
	public int hashCode();

	@Override
	public CacheModel<net.gbcoder.gblib.model.Book> toCacheModel();

	@Override
	public net.gbcoder.gblib.model.Book toEscapedModel();

	@Override
	public net.gbcoder.gblib.model.Book toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}